apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: three-tier
spec:
  type: NodePort          # <--- CHANGED: This prepares the bridge
  selector:
    role: api
  ports:
    - protocol: TCP
      port: 3000          # Internal usage inside the cluster
      targetPort: 3000    # The port your container is running on
      nodePort: 31000     # <--- ADDED: The "Bridge" port for AWS