apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: three-tier
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-stickiness-policy-name: "CookiePolicy"
    service.beta.kubernetes.io/aws-load-balancer-stickiness-policy-expiration-period: "3600"
    service.beta.kubernetes.io/aws-load-balancer-stickiness-type: "lb_cookie"
spec:
  ports:
  - port: 3000        # The port you want to expose to the internet
    targetPort: 3000  # The port your container listens on
    protocol: TCP
  type: LoadBalancer  # <--- CHANGE THIS from ClusterIP
  selector:
    role: api
