apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: three-tier
spec:
  ports:
  - port: 3000        # The port you want to expose to the internet
    targetPort: 3000  # The port your container listens on
    protocol: TCP
  type: LoadBalancer  # <--- CHANGE THIS from ClusterIP
  selector:
    role: api
